local ingredients = {
    { name = "ice", cal = 2.34375,
        tags = { frozen = 1,},
    },
    { name = "twigs", cal = 9.375,
        tags = { inedible = 1,},
    },
    { name = "bird_egg", cal = 9.375,
        tags = { egg = 1,},
    },
    { name = "bird_egg_cooked", cal = 9.375,
        tags = { egg = 1,},
    },
    { name = "honey", cal = 9.375,
        tags = { sweetener = 1,},
    },
    { name = "berries", cal = 9.375,
        tags = { fruit = 0.5,},
    },
    { name = "berries_cooked", cal = 9.375,
        tags = { fruit = 0.5,},
    },
    { name = "drumstick_cooked", cal = 12.5,
        tags = { meats = 0.5,},
    },
    { name = "cookedsmallmeat", cal = 12.5,
        tags = { meats = 0.5,},
    },
    { name = "drumstick", cal = 12.5,
        tags = { meats = 0.5,},
    },
    { name = "cave_banana_cooked", cal = 12.5,
        tags = { fruit = 1,},
    },
    { name = "pondfish", cal = 12.5,
        tags = { meats = 0.5, fish = 0.5,},
    },
    { name = "fishmeat_small_cooked", cal = 12.5,
        tags = { meats = 0.5, fish = 0.5,},
    },
    { name = "froglegs", cal = 12.5,
        tags = { meats = 0.5,},
    },
    { name = "fish", cal = 12.5,
        tags = { meats = 1, fish = 1,},
    },
    { name = "cave_banana", cal = 12.5,
        tags = { fruit = 1,},
    },
    { name = "smallmeat", cal = 12.5,
        tags = { meats = 0.5,},
    },
    { name = "rock_avocado_fruit_ripe", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "fishmeat_small", cal = 12.5,
        tags = { meats = 0.5, fish = 0.5,},
    },
    { name = "smallmeat_dried", cal = 12.5,
        tags = { meats = 0.5,},
    },
    { name = "fish_cooked", cal = 12.5,
        tags = { meats = 1, fish = 1,},
    },
    { name = "berries_juicy_cooked", cal = 12.5,
        tags = { fruit = 0.5,},
    },
    { name = "berries_juicy", cal = 12.5,
        tags = { fruit = 0.5,},
    },
    { name = "carrot", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "rock_avocado_fruit_ripe_cooked", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "froglegs_cooked", cal = 12.5,
        tags = { meats = 0.5,},
    },
    { name = "plantmeat_cooked", cal = 18.75,
        tags = { meats = 1,},
    },
    { name = "monstermeat", cal = 18.75,
        tags = { monster = 1, meats = 1,},
    },
    { name = "cookedmonstermeat", cal = 18.75,
        tags = { monster = 1, meats = 1,},
    },
    { name = "monstermeat_dried", cal = 18.75,
        tags = { monster = 1, meats = 1,},
    },
    { name = "tallbirdegg", cal = 25,
        tags = { egg = 4,},
    },
    { name = "fishmeat", cal = 25,
        tags = { meats = 1, fish = 1,},
    },
    { name = "fishmeat_cooked", cal = 25,
        tags = { meats = 1, fish = 1,},
    },
    { name = "cookedmeat", cal = 25,
        tags = { meats = 1,},
    },
    { name = "meat_dried", cal = 25,
        tags = { meats = 1,},
    },
    { name = "tallbirdegg_cooked", cal = 25,
        tags = { egg = 4,},
    },
    { name = "meat", cal = 25,
        tags = { meats = 1,},
    },
    { name = "nightmarefuel",
        tags = { inedible = 1, magic = 1,},
    },
    { name = "boneshard",
        tags = { inedible = 1,},
    },
    { name = "forgetmelots", cal = 0,
        tags = { decoration = 1,},
    },
    { name = "refined_dust", cal = 1,
        tags = { decoration = 2,},
    },
    { name = "dragonfruit_cooked", cal = 9.375,
        tags = { fruit = 1,},
    },
    { name = "pomegranate_cooked", cal = 9.375,
        tags = { fruit = 1,},
    },
    { name = "pondeel_cooked", cal = 9.375,
        tags = { meats = 0.5, fish = 1,},
    },
    { name = "onion", cal = 9.375,
        tags = { veggie = 1,},
    },
    { name = "onion_cooked", cal = 9.375,
        tags = { veggie = 1,},
    },
    { name = "eel", cal = 9.375,
        tags = { meats = 0.5, fish = 1,},
    },
    { name = "butterflywings", cal = 9.375,
        tags = { decoration = 2,},
    },
    { name = "kelp", cal = 9.375,
        tags = { veggie = 0.5,},
    },
    { name = "dragonfruit", cal = 9.375,
        tags = { fruit = 1,},
    },
    { name = "pondeel", cal = 9.375,
        tags = { meats = 0.5, fish = 1,},
    },
    { name = "pepper_cooked", cal = 9.375,
        tags = { veggie = 1,},
    },
    { name = "garlic_cooked", cal = 9.375,
        tags = { veggie = 1,},
    },
    { name = "moonbutterflywings", cal = 9.375,
        tags = { decoration = 2,},
    },
    { name = "acorn", cal = 9.375,
        tags = { seed = 1,},
    },
    { name = "pomegranate", cal = 9.375,
        tags = { fruit = 1,},
    },
    { name = "eel_cooked", cal = 9.375,
        tags = { meats = 0.5, fish = 1,},
    },
    { name = "acorn_cooked", cal = 9.375,
        tags = { seed = 1,},
    },
    { name = "kelp_cooked", cal = 9.375,
        tags = { veggie = 0.5,},
    },
    { name = "garlic", cal = 9.375,
        tags = { veggie = 1,},
    },
    { name = "pepper", cal = 9.375,
        tags = { veggie = 1,},
    },
    { name = "kelp_dried", cal = 9.375,
        tags = { veggie = 0.5,},
    },
    { name = "asparagus_cooked", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "royal_jelly", cal = 12.5,
        tags = { sweetener = 3,},
    },
    { name = "potato", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "green_cap_cooked", cal = 12.5,
        tags = { veggie = 0.5,},
    },
    { name = "green_cap", cal = 12.5,
        tags = { veggie = 0.5,},
    },
    { name = "oceanfish_small_7_inv", cal = 12.5,
        tags = { meats = 0.5, fish = 0.5,},
    },
    { name = "red_cap_cooked", cal = 12.5,
        tags = { veggie = 0.5,},
    },
    { name = "milkywhites", cal = 12.5,
        tags = { dairy = 1,},
    },
    { name = "oceanfish_small_8_inv", cal = 12.5,
        tags = { meats = 0.5, fish = 0.5,},
    },
    { name = "watermelon_cooked", cal = 12.5,
        tags = { fruit = 1,},
    },
    { name = "moon_cap_cooked", cal = 12.5,
        tags = { veggie = 0.5,},
    },
    { name = "tomato", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "oceanfish_small_9_inv", cal = 12.5,
        tags = { meats = 0.5, fish = 0.5,},
    },
    { name = "oceanfish_small_3_inv", cal = 12.5,
        tags = { meats = 0.5, fish = 0.5,},
    },
    { name = "cactus_meat_cooked", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "oceanfish_small_6_inv", cal = 12.5,
        tags = { meats = 0.5, fish = 0.5,},
    },
    { name = "oceanfish_small_4_inv", cal = 12.5,
        tags = { meats = 0.5, fish = 0.5,},
    },
    { name = "moon_cap", cal = 12.5,
        tags = { veggie = 0.5,},
    },
    { name = "batnose_dried", cal = 12.5,
        tags = { meats = 0.5,},
    },
    { name = "asparagus", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "tomato_cooked", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "cutlichen", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "cactus_meat", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "watermelon", cal = 12.5,
        tags = { fruit = 1,},
    },
    { name = "cutlichen_cooked", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "oceanfish_small_1_inv", cal = 12.5,
        tags = { meats = 0.5, fish = 0.5,},
    },
    { name = "fig_cooked", cal = 12.5,
        tags = { fruit = 0.5,},
    },
    { name = "red_cap", cal = 12.5,
        tags = { veggie = 0.5,},
    },
    { name = "oceanfish_small_2_inv", cal = 12.5,
        tags = { meats = 0.5, fish = 0.5,},
    },
    { name = "batwing_cooked", cal = 12.5,
        tags = { meats = 0.5,},
    },
    { name = "barnacle", cal = 12.5,
        tags = { meats = 0.25, fish = 0.25,},
    },
    { name = "batwing", cal = 12.5,
        tags = { meats = 0.5,},
    },
    { name = "wormlight_lesser", cal = 12.5,
        tags = { fruit = 0.5,},
    },
    { name = "batnose_cooked", cal = 12.5,
        tags = { meats = 0.5,},
    },
    { name = "barnacle_cooked", cal = 12.5,
        tags = { meats = 0.25, fish = 0.25,},
    },
    { name = "goatmilk", cal = 12.5,
        tags = { dairy = 1,},
    },
    { name = "carrot_cooked", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "oceanfish_small_5_inv", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "plantmeat", cal = 12.5,
        tags = { meats = 1,},
    },
    { name = "batnose", cal = 12.5,
        tags = { meats = 0.5,},
    },
    { name = "cactus_flower", cal = 12.5,
        tags = { veggie = 0.5,},
    },
    { name = "potato_cooked", cal = 12.5,
        tags = { veggie = 1,},
    },
    { name = "blue_cap_cooked", cal = 12.5,
        tags = { veggie = 0.5,},
    },
    { name = "blue_cap", cal = 12.5,
        tags = { veggie = 0.5,},
    },
    { name = "fig", cal = 12.5,
        tags = { fruit = 0.5,},
    },
    { name = "oceanfish_medium_6_inv", cal = 25,
        tags = { meats = 1, fish = 1,},
    },
    { name = "durian", cal = 25,
        tags = { fruit = 1, monster = 1,},
    },
    { name = "oceanfish_medium_3_inv", cal = 25,
        tags = { meats = 1, fish = 1,},
    },
    { name = "corn_cooked", cal = 25,
        tags = { veggie = 1,},
    },
    { name = "oceanfish_medium_7_inv", cal = 25,
        tags = { meats = 1, fish = 1,},
    },
    { name = "eggplant", cal = 25,
        tags = { veggie = 1,},
    },
    { name = "oceanfish_medium_1_inv", cal = 25,
        tags = { meats = 1, fish = 1,},
    },
    { name = "oceanfish_medium_5_inv", cal = 25,
        tags = { veggie = 1,},
    },
    { name = "oceanfish_medium_9_inv", cal = 25,
        tags = { meats = 1, fish = 1,},
    },
    { name = "wormlight", cal = 25,
        tags = { fruit = 1,},
    },
    { name = "butter", cal = 25,
        tags = { fat = 1, dairy = 1,},
    },
    { name = "corn", cal = 25,
        tags = { veggie = 1,},
    },
    { name = "oceanfish_medium_2_inv", cal = 25,
        tags = { meats = 1, fish = 1,},
    },
    { name = "oceanfish_medium_8_inv", cal = 25,
        tags = { frozen = 1, meats = 1, fish = 1,},
    },
    { name = "eggplant_cooked", cal = 25,
        tags = { veggie = 1,},
    },
    { name = "durian_cooked", cal = 25,
        tags = { fruit = 1, monster = 1,},
    },
    { name = "oceanfish_medium_4_inv", cal = 25,
        tags = { meats = 1, fish = 1,},
    },
    { name = "trunk_summer", cal = 37.5,
        tags = { meats = 1,},
    },
    { name = "trunk_winter", cal = 37.5,
        tags = { meats = 1,},
    },
    { name = "pumpkin", cal = 37.5,
        tags = { veggie = 1,},
    },
    { name = "pumpkin_cooked", cal = 37.5,
        tags = { veggie = 1,},
    },
    { name = "mandrake", cal = 75,
        tags = { veggie = 1, magic = 1,},
    },
    { name = "trunk_cooked", cal = 75,
        tags = { meats = 1,},
    },
    { name = "cookedmandrake", cal = 150,
        tags = { veggie = 1, magic = 1,},
    },
    { name = "honeycomb",
        tags = { sweetener = 1,},
    },
    { name = "mole",
        tags = { meats = 0.5,},
    },
    { name = "lightninggoathorn",
        tags = { inedible = 1,},
    },
    { name = "wobster_sheller_land",
        tags = { meats = 1, fish = 1,},
    },
}
return ingredients