local preparedfoods = {
    { cal = 0, name = "powcake",
        { name = "twigs and honey and (corn or corn_cooked or oceanfish_small_5_inv or oceanfish_medium_5_inv) end,",
            id = 22, weight = 0, },
        needs = {
            or_needs = {
                {
                    { atleast = 0.01, atmost = 1000, cal = 12.5, name = "oceanfish_small_5_inv", },
                    { atleast = 0.01, atmost = 1000, cal = 25, name = "oceanfish_medium_5_inv", },
                    { atleast = 0.01, atmost = 1000, cal = 25, name = "corn", },
                },
            },
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "honey", },
                { atmost = 1000, atleast = 0.01, name = "twigs", },
            },
        },
        priority = { cal = -33.59375, default = -1, },
        best_recipe = { cal = 33.59375,
            slots = {
                { cal = 9.375, name = "honey", },
                { cal = 9.375, name = "twigs", },
                { cal = 12.5, name = "oceanfish_small_5_inv", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 18.75, name = "asparagussoup",
        { name = "(asparagus or asparagus_cooked) and veggie and veggie > 2 and not meats and not inedible end,", id = 34,
            weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "inedible", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "asparagus", },
                { atmost = 1000, atleast = 2.01, name = "veggie", },
            },
        },
        priority = { cal = -31.25, default = -1, },
        best_recipe = { cal = 50.0,
            slots = {
                { cal = 12.5, name = "asparagus", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
            },
        },
    },
    { cal = 12.5, name = "trailmix",
        { name = "(acorn or acorn_cooked) and seed and seed >= 1 and (berries or berries_cooked or berries_juicy or berries_juicy_cooked) and fruit and fruit >= 1 and not meats and not veggie and not egg and not dairy end,",
            id = 28, weight = 0, },
        needs = {
            or_needs = {
                {
                    { atleast = 0.01, atmost = 1000, cal = 9.375, name = "berries", },
                    { atleast = 0.01, atmost = 1000, cal = 12.5, name = "berries_juicy", },
                },
            },
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "veggie", },
                { atmost = 0.01, atleast = 0, name = "egg", },
                { atmost = 0.01, atleast = 0, name = "dairy", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "acorn", },
                { atmost = 1000, atleast = 1, name = "fruit", },
                { atmost = 1000, atleast = 1, name = "seed", },
            },
        },
        priority = { cal = -28.125, default = -1, },
        best_recipe = { cal = 40.625,
            slots = {
                { cal = 9.375, name = "acorn", },
                { cal = 12.5, name = "cave_banana_cooked", },
                { cal = 9.375, name = "acorn", },
                { cal = 9.375, name = "berries", },
            },
        },
    },
    { cal = 12.5, name = "flowersalad",
        { name = "cactus_flower and veggie and veggie >= 2 and not meats and not inedible and not egg and not sweetener and not fruit end,",
            id = 25, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "inedible", },
                { atmost = 0.01, atleast = 0, name = "egg", },
                { atmost = 0.01, atleast = 0, name = "sweetener", },
                { atmost = 0.01, atleast = 0, name = "fruit", },
            },
            must_needs = {
                { atmost = 1000, atleast = 2, name = "veggie", },
                { atmost = 1000, atleast = 0.01, name = "cactus_flower", },
            },
        },
        priority = { cal = -27.34375, default = -1, },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 12.5, name = "cactus_flower", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 25, name = "shroomcake",
        { name = "moon_cap and red_cap and blue_cap and green_cap end,", id = 55, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "green_cap", },
                { atmost = 1000, atleast = 0.01, name = "blue_cap", },
                { atmost = 1000, atleast = 0.01, name = "red_cap", },
                { atmost = 1000, atleast = 0.01, name = "moon_cap", },
            },
        },
        priority = { cal = -25.0, default = -1, },
        best_recipe = { cal = 50.0,
            slots = {
                { cal = 12.5, name = "green_cap", },
                { cal = 12.5, name = "blue_cap", },
                { cal = 12.5, name = "red_cap", },
                { cal = 12.5, name = "moon_cap", },
            },
        },
    },
    { cal = 37.5, name = "hotchili",
        { name = "meats and meats >= 1.5 and veggie and veggie >= 1.5 end,", id = 29, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 1.5, name = "veggie", },
                { atmost = 1000, atleast = 1.5, name = "meats", },
            },
        },
        priority = { cal = -25.0, default = -1, },
        best_recipe = { cal = 62.5,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 18.75, name = "monstermeat", },
                { cal = 18.75, name = "monstermeat", },
            },
        },
    },
    { cal = 37.5, name = "pumpkincookie",
        { name = "(pumpkin or pumpkin_cooked) and sweetener and sweetener >= 2 end,", id = 3, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "pumpkin", },
                { atmost = 1000, atleast = 2, name = "sweetener", },
            },
        },
        priority = { cal = -21.09375, default = -1, },
        best_recipe = { cal = 58.59375,
            slots = {
                { cal = 37.5, name = "pumpkin", },
                { cal = 9.375, name = "honey", },
                { cal = 9.375, name = "honey", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 0, name = "jellybean",
        { name = "royal_jelly and not inedible and not monster end,", id = 31, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "inedible", },
                { atmost = 0.01, atleast = 0, name = "monster", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "royal_jelly", },
            },
        },
        priority = { cal = -19.53125, default = -1, },
        best_recipe = { cal = 19.53125,
            slots = {
                { cal = 12.5, name = "royal_jelly", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "lobsterdinner",
        { name = "wobster_sheller_land and butter and (meats and meats >= 1.0) and (fish and fish >= 1.0) and not frozen end,",
            id = 46, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "frozen", },
            },
            must_needs = {
                { atmost = 1000, atleast = 1, name = "meats", },
                { atmost = 1000, atleast = 1, name = "fish", },
                { atmost = 1000, atleast = 0.01, name = "butter", },
                { atmost = 1000, atleast = 0.01, name = "wobster_sheller_land", },
            },
        },
        priority = { cal = -18.75, default = -1, },
        best_recipe = { cal = 56.25,
            slots = {
                { cal = 18.75, name = "monstermeat", },
                { cal = 12.5, name = "fish", },
                { cal = 25, name = "butter", },
                { name = "wobster_sheller_land", },
            },
        },
    },
    { cal = 25, name = "figkabab",
        { name = "(fig or fig_cooked) and twigs and meats and meats >= 1 and (not monster or monster <= 1) end,", id = 59,
            weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 1, atleast = 0.01, name = "monster", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "fig", },
                { atmost = 1000, atleast = 1, name = "meats", },
                { atmost = 1000, atleast = 0.01, name = "twigs", },
            },
        },
        priority = { cal = -17.96875, default = -1, },
        best_recipe = { cal = 42.96875,
            slots = {
                { cal = 12.5, name = "fig", },
                { cal = 18.75, name = "monstermeat", },
                { cal = 9.375, name = "twigs", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 25, name = "vegstinger",
        { name = "(asparagus or asparagus_cooked or tomato or tomato_cooked) and veggie and veggie > 2 and frozen and not meats and not inedible and not egg end,",
            id = 35, weight = 0, },
        needs = {
            or_needs = {
                {
                    { atmost = 1000, atleast = 0.01, name = "tomato", },
                    { atmost = 1000, atleast = 0.01, name = "asparagus", },
                },
            },
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "inedible", },
                { atmost = 0.01, atleast = 0, name = "egg", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "frozen", },
                { atmost = 1000, atleast = 2.01, name = "veggie", },
            },
        },
        priority = { cal = -14.84375, default = -1, },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 2.34375, name = "ice", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
            },
        },
    },
    { cal = 25, name = "fruitmedley",
        { name = "fruit and fruit >= 3 and not meats and not veggie end,", id = 18, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "veggie", },
            },
            must_needs = {
                { atmost = 1000, atleast = 3, name = "fruit", },
            },
        },
        priority = { cal = -14.84375, default = -1, },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 12.5, name = "cave_banana_cooked", },
                { cal = 12.5, name = "cave_banana_cooked", },
                { cal = 12.5, name = "cave_banana_cooked", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "stuffedeggplant",
        { name = "(eggplant or eggplant_cooked) and veggie and veggie > 1 end,", id = 4, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "eggplant", },
                { atmost = 1000, atleast = 1.01, name = "veggie", },
            },
        },
        priority = { cal = -14.84375, default = -1, },
        best_recipe = { cal = 52.34375,
            slots = {
                { cal = 25, name = "eggplant", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 0, name = "sweettea",
        { name = "forgetmelots and sweetener and frozen and not monster and not veggie and not meats and not fish and not egg and not fat and not dairy and not inedible end,",
            id = 56, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "monster", },
                { atmost = 0.01, atleast = 0, name = "veggie", },
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "fish", },
                { atmost = 0.01, atleast = 0, name = "egg", },
                { atmost = 0.01, atleast = 0, name = "fat", },
                { atmost = 0.01, atleast = 0, name = "dairy", },
                { atmost = 0.01, atleast = 0, name = "inedible", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "frozen", },
                { atmost = 1000, atleast = 0.01, name = "sweetener", },
                { atmost = 1000, atleast = 0.01, name = "forgetmelots", },
            },
        },
        priority = { cal = -14.0625, default = -1, },
        best_recipe = { cal = 14.0625,
            slots = {
                { cal = 2.34375, name = "ice", },
                { cal = 9.375, name = "honey", },
                { cal = 0, name = "forgetmelots", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 12.5, name = "watermelonicle",
        { name = "watermelon and frozen and twigs and not meats and not veggie and not egg end,", id = 27, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "veggie", },
                { atmost = 0.01, atleast = 0, name = "egg", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "twigs", },
                { atmost = 1000, atleast = 0.01, name = "frozen", },
                { atmost = 1000, atleast = 0.01, name = "watermelon", },
            },
        },
        priority = { cal = -14.0625, default = -1, },
        best_recipe = { cal = 26.5625,
            slots = {
                { cal = 9.375, name = "twigs", },
                { cal = 2.34375, name = "ice", },
                { cal = 12.5, name = "watermelon", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 12.5, name = "bananapop",
        { name = "(cave_banana or cave_banana_cooked) and frozen and twigs and not meats and not fish end,", id = 36,
            weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "fish", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "cave_banana", },
                { atmost = 1000, atleast = 0.01, name = "twigs", },
                { atmost = 1000, atleast = 0.01, name = "frozen", },
            },
        },
        priority = { cal = -14.0625, default = -1, },
        best_recipe = { cal = 26.5625,
            slots = {
                { cal = 12.5, name = "cave_banana", },
                { cal = 9.375, name = "twigs", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 18.75, name = "frognewton",
        { name = "(fig or fig_cooked) and (froglegs or froglegs_cooked) end,", id = 60, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "fig", },
                { atmost = 1000, atleast = 0.01, name = "froglegs", },
            },
        },
        priority = { cal = -10.9375, default = -1, },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 12.5, name = "fig", },
                { cal = 12.5, name = "froglegs", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "leafymeatburger",
        { name = "(plantmeat or plantmeat_cooked) and (onion or onion_cooked) and veggie and veggie >= 2 end,", id = 52,
            weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "plantmeat", },
                { atmost = 1000, atleast = 0.01, name = "onion", },
                { atmost = 1000, atleast = 2, name = "veggie", },
            },
        },
        priority = { cal = -9.375, default = -1, },
        best_recipe = { cal = 46.875,
            slots = {
                { cal = 12.5, name = "plantmeat", },
                { cal = 9.375, name = "onion", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
            },
        },
    },
    { cal = 0, name = "wetgoop",
        { name = "true end,", id = 24, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "true", },
            },
        },
        priority = { cal = -9.375, default = -1, },
        best_recipe = { cal = 9.375,
            slots = {
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "waffles",
        { name = "butter and (berries or berries_cooked or berries_juicy or berries_juicy_cooked) and egg end,", id = 20,
            weight = 0, },
        needs = {
            or_needs = {
                {
                    { atleast = 0.01, atmost = 1000, cal = 9.375, name = "berries", },
                    { atleast = 0.01, atmost = 1000, cal = 12.5, name = "berries_juicy", },
                },
            },
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "egg", },
                { atmost = 1000, atleast = 0.01, name = "butter", },
            },
        },
        priority = { cal = -8.59375, default = -1, },
        best_recipe = { cal = 46.09375,
            slots = {
                { cal = 9.375, name = "bird_egg_cooked", },
                { cal = 25, name = "butter", },
                { cal = 9.375, name = "berries", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 25, name = "pepperpopper",
        { name = "(pepper or pepper_cooked) and meats and meats <= 1.5 and not inedible end,", id = 41, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "inedible", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "pepper", },
                { atmost = 1.5, atleast = 0.01, name = "meats", },
            },
        },
        priority = { cal = -7.8125, default = -1, },
        best_recipe = { cal = 32.8125,
            slots = {
                { cal = 9.375, name = "pepper", },
                { cal = 18.75, name = "monstermeat", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "leafymeatsouffle",
        { name = "(plantmeat >= 2 ) and sweetener and sweetener >= 2 end,", id = 53, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 2, name = "plantmeat", },
                { atmost = 1000, atleast = 2, name = "sweetener", },
            },
        },
        priority = { cal = -6.25, default = -1, },
        best_recipe = { cal = 43.75,
            slots = {
                { cal = 12.5, name = "plantmeat", },
                { cal = 12.5, name = "plantmeat", },
                { cal = 9.375, name = "honey", },
                { cal = 9.375, name = "honey", },
            },
        },
    },
    { cal = 37.5, name = "surfnturf",
        { name = "meats and meats >= 2.5 and fish and fish >= 1.5 and not frozen end,", id = 44, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "frozen", },
            },
            must_needs = {
                { atmost = 1000, atleast = 1.5, name = "fish", },
                { atmost = 1000, atleast = 2.5, name = "meats", },
            },
        },
        priority = { cal = -6.25, default = -1, },
        best_recipe = { cal = 43.75,
            slots = {
                { cal = 12.5, name = "fish", },
                { cal = 12.5, name = "fish", },
                { cal = 9.375, name = "twigs", },
                { cal = 9.375, name = "twigs", },
            },
        },
    },
    { cal = 37.5, name = "perogies",
        { name = "egg and meats and veggie and veggie >= 0.5 and not inedible end,", id = 14, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "inedible", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.5, name = "veggie", },
                { atmost = 1000, atleast = 0.01, name = "meats", },
                { atmost = 1000, atleast = 0.01, name = "egg", },
            },
        },
        priority = { cal = -5.46875, default = -1, },
        best_recipe = { cal = 42.96875,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 18.75, name = "monstermeat", },
                { cal = 9.375, name = "bird_egg_cooked", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 25, name = "taffy",
        { name = "sweetener and sweetener >= 3 and not meats end,", id = 2, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
            },
            must_needs = {
                { atmost = 1000, atleast = 3, name = "sweetener", },
            },
        },
        priority = { cal = -5.46875, default = -1, },
        best_recipe = { cal = 30.46875,
            slots = {
                { cal = 9.375, name = "honey", },
                { cal = 9.375, name = "honey", },
                { cal = 9.375, name = "honey", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "monsterlasagna",
        { name = "monster and monster >= 2 and not inedible end,", id = 21, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "inedible", },
            },
            must_needs = {
                { atmost = 1000, atleast = 2, name = "monster", },
            },
        },
        priority = { cal = -4.6875, default = -1, },
        best_recipe = { cal = 42.1875,
            slots = {
                { cal = 18.75, name = "cookedmonstermeat", },
                { cal = 18.75, name = "cookedmonstermeat", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 25, name = "ceviche",
        { name = "fish and fish >= 2 and frozen and not inedible and not egg end,", id = 39, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "inedible", },
                { atmost = 0.01, atleast = 0, name = "egg", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "frozen", },
                { atmost = 1000, atleast = 2, name = "fish", },
            },
        },
        priority = { cal = -4.6875, default = -1, },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 2.34375, name = "ice", },
                { cal = 12.5, name = "fish", },
                { cal = 12.5, name = "fish", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 25, name = "bananajuice",
        { name = "(cave_banana >= 2) and not meats and not fish and not monster end,", id = 38, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "fish", },
                { atmost = 0.01, atleast = 0, name = "monster", },
            },
            must_needs = {
                { atmost = 1000, atleast = 2, name = "cave_banana", },
            },
        },
        priority = { cal = -4.6875, default = -1, },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 12.5, name = "cave_banana", },
                { cal = 12.5, name = "cave_banana", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 18.75, name = "unagi",
        { name = "(cutlichen or kelp or kelp_cooked or kelp_dried) and (eel or eel_cooked or pondeel) end,", id = 23,
            weight = 0, },
        needs = {
            or_needs = {
                {
                    { atleast = 0.01, atmost = 1000, cal = 9.375, name = "kelp_dried", },
                    { atleast = 0.01, atmost = 1000, cal = 9.375, name = "kelp", },
                    { atleast = 0.01, atmost = 1000, cal = 12.5, name = "cutlichen", },
                },
                {
                    { atleast = 0.01, atmost = 1000, cal = 9.375, name = "pondeel", },
                    { atleast = 0.01, atmost = 1000, cal = 9.375, name = "eel", },
                },
            },
            not_tags = {},
            must_needs = {},
        },
        priority = { cal = -4.6875, default = -1, },
        best_recipe = { cal = 23.4375,
            slots = {
                { cal = 9.375, name = "kelp_dried", },
                { cal = 9.375, name = "pondeel", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "kabobs",
        { name = "meats and twigs and (not monster or monster <= 1) and (inedible and inedible <= 1) end,", id = 9,
            weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 1, atleast = 0.01, name = "monster", },
            },
            must_needs = {
                { atmost = 1, atleast = 0.01, name = "inedible", },
                { atmost = 1000, atleast = 0.01, name = "twigs", },
                { atmost = 1000, atleast = 0.01, name = "meats", },
            },
        },
        priority = { cal = -2.34375, default = -1, },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 9.375, name = "twigs", },
                { cal = 9.375, name = "twigs", },
                { cal = 18.75, name = "monstermeat", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "seafoodgumbo",
        { name = "fish and fish > 2 end,", id = 43, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 2.01, name = "fish", },
            },
        },
        priority = { cal = -2.34375, default = -1, },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 12.5, name = "fish", },
                { cal = 12.5, name = "fish", },
                { cal = 12.5, name = "fish", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 25, name = "salsa",
        { name = "(tomato or tomato_cooked) and (onion or onion_cooked) and not meats and not inedible and not egg end,",
            id = 40, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "inedible", },
                { atmost = 0.01, atleast = 0, name = "egg", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "tomato", },
                { atmost = 1000, atleast = 0.01, name = "onion", },
            },
        },
        priority = { cal = -1.5625, default = -1, },
        best_recipe = { cal = 26.5625,
            slots = {
                { cal = 12.5, name = "tomato", },
                { cal = 9.375, name = "onion", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 25, name = "icecream",
        { name = "frozen and dairy and sweetener and not meats and not veggie and not inedible and not egg end,", id = 26,
            weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "veggie", },
                { atmost = 0.01, atleast = 0, name = "inedible", },
                { atmost = 0.01, atleast = 0, name = "egg", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "sweetener", },
                { atmost = 1000, atleast = 0.01, name = "dairy", },
                { atmost = 1000, atleast = 0.01, name = "frozen", },
            },
        },
        priority = { cal = -1.5625, default = -1, },
        best_recipe = { cal = 26.5625,
            slots = {
                { cal = 9.375, name = "honey", },
                { cal = 12.5, name = "milkywhites", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 18.75, name = "frozenbananadaiquiri",
        { name = "(cave_banana or cave_banana_cooked) and (frozen and frozen >= 1) and not meats and not fish end,",
            id = 37, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "fish", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "cave_banana", },
                { atmost = 1000, atleast = 1, name = "frozen", },
            },
        },
        priority = { cal = -0.78125, default = -1, },
        best_recipe = { cal = 19.53125,
            slots = {
                { cal = 12.5, name = "cave_banana", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "mashedpotatoes",
        { name = "((potato and potato > 1) or (potato_cooked and potato_cooked > 1) or (potato and potato_cooked)) and (garlic or garlic_cooked) and not meats and not inedible end,",
            id = 33, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "inedible", },
            },
            must_needs = {
                { atmost = 1000, atleast = 1.01, name = "potato", },
                { atmost = 1000, atleast = 0.01, name = "garlic", },
            },
        },
        priority = { cal = 0.78125, default = -1, },
        best_recipe = { cal = 36.71875,
            slots = {
                { cal = 12.5, name = "potato", },
                { cal = 12.5, name = "potato", },
                { cal = 9.375, name = "garlic", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 56.25, name = "koalefig_trunk",
        { name = "(trunk_summer or trunk_cooked or trunk_winter) and (fig or fig_cooked) end,", id = 57, weight = 0, },
        needs = {
            or_needs = {
                {
                    { atleast = 0.01, atmost = 1000, cal = 37.5, name = "trunk_winter", },
                    { atleast = 0.01, atmost = 1000, cal = 37.5, name = "trunk_summer", },
                    { atleast = 0.01, atmost = 1000, cal = 75, name = "trunk_cooked", },
                },
            },
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "fig", },
            },
        },
        priority = { cal = 1.5625, default = -1, },
        best_recipe = { cal = 54.6875,
            slots = {
                { cal = 12.5, name = "fig", },
                { cal = 37.5, name = "trunk_winter", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "fishsticks",
        { name = "fish and twigs and (inedible and inedible <= 1) end,", id = 5, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1, atleast = 0.01, name = "inedible", },
                { atmost = 1000, atleast = 0.01, name = "twigs", },
                { atmost = 1000, atleast = 0.01, name = "fish", },
            },
        },
        priority = { cal = 3.90625, default = -1, },
        best_recipe = { cal = 33.59375,
            slots = {
                { cal = 9.375, name = "twigs", },
                { cal = 9.375, name = "twigs", },
                { cal = 12.5, name = "fish", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "barnaclesushi",
        { name = "(barnacle or barnacle_cooked) and (kelp or kelp_cooked) and egg and egg >= 1 end,", id = 48, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "barnacle", },
                { atmost = 1000, atleast = 0.01, name = "kelp", },
                { atmost = 1000, atleast = 1, name = "egg", },
            },
        },
        priority = { cal = 3.90625, default = -1, },
        best_recipe = { cal = 33.59375,
            slots = {
                { cal = 12.5, name = "barnacle", },
                { cal = 9.375, name = "kelp", },
                { cal = 9.375, name = "bird_egg_cooked", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "potatotornado",
        { name = "(potato or potato_cooked) and twigs and (not monster or monster <= 1) and not meats and (inedible and inedible <= 2) end,",
            id = 32, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 1, atleast = 0.01, name = "monster", },
                { atmost = 0.01, atleast = 0, name = "meats", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "potato", },
                { atmost = 2, atleast = 0.01, name = "inedible", },
                { atmost = 1000, atleast = 0.01, name = "twigs", },
            },
        },
        priority = { cal = 3.90625, default = -1, },
        best_recipe = { cal = 33.59375,
            slots = {
                { cal = 12.5, name = "potato", },
                { cal = 9.375, name = "twigs", },
                { cal = 9.375, name = "twigs", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 25, name = "beefalotreat",
        { name = "inedible and seed and forgetmelots and not monster and not meats and not fish and not egg and not fat and not dairy and not magic end,",
            id = 66, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "monster", },
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "fish", },
                { atmost = 0.01, atleast = 0, name = "egg", },
                { atmost = 0.01, atleast = 0, name = "fat", },
                { atmost = 0.01, atleast = 0, name = "dairy", },
                { atmost = 0.01, atleast = 0, name = "magic", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "forgetmelots", },
                { atmost = 1000, atleast = 0.01, name = "seed", },
                { atmost = 1000, atleast = 0.01, name = "inedible", },
            },
        },
        priority = { cal = 3.90625, default = -1, },
        best_recipe = { cal = 21.09375,
            slots = {
                { cal = 0, name = "forgetmelots", },
                { cal = 9.375, name = "acorn", },
                { cal = 9.375, name = "twigs", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "honeynuggets",
        { name = "honey and meats and meats <= 1.5 and not inedible end,", id = 6, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "inedible", },
            },
            must_needs = {
                { atmost = 1.5, atleast = 0.01, name = "meats", },
                { atmost = 1000, atleast = 0.01, name = "honey", },
            },
        },
        priority = { cal = 4.6875, default = -1, },
        best_recipe = { cal = 32.8125,
            slots = {
                { cal = 18.75, name = "monstermeat", },
                { cal = 9.375, name = "honey", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 25, name = "ratatouille",
        { name = "not meats and veggie and veggie >= 0.5 and not inedible end,", id = 16, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "inedible", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.5, name = "veggie", },
            },
        },
        priority = { cal = 5.46875, default = -1, },
        best_recipe = { cal = 19.53125,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "fishtacos",
        { name = "fish and (corn or corn_cooked or oceanfish_small_5_inv or oceanfish_medium_5_inv) end,", id = 19,
            weight = 0, },
        needs = {
            or_needs = {
                {
                    { atleast = 0.01, atmost = 1000, cal = 12.5, name = "oceanfish_small_5_inv", },
                    { atleast = 0.01, atmost = 1000, cal = 25, name = "oceanfish_medium_5_inv", },
                    { atleast = 0.01, atmost = 1000, cal = 25, name = "corn", },
                },
            },
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "fish", },
            },
        },
        priority = { cal = 7.8125, default = -1, },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 12.5, name = "fish", },
                { cal = 12.5, name = "oceanfish_small_5_inv", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "leafloaf",
        { name = "(plantmeat >= 2 ) end,", id = 51, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 2, name = "plantmeat", },
            },
        },
        priority = { cal = 7.8125, default = -1, },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 12.5, name = "plantmeat", },
                { cal = 12.5, name = "plantmeat", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "barnaclepita",
        { name = "(barnacle or barnacle_cooked) and veggie and veggie >= 0.5 end,", id = 47, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "barnacle", },
                { atmost = 1000, atleast = 0.5, name = "veggie", },
            },
        },
        priority = { cal = 7.8125, default = -1, },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 12.5, name = "barnacle", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "frogglebunwich",
        { name = "(froglegs or froglegs_cooked) and veggie and veggie >= 0.5 end,", id = 1, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "froglegs", },
                { atmost = 1000, atleast = 0.5, name = "veggie", },
            },
        },
        priority = { cal = 7.8125, default = -1, },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 12.5, name = "froglegs", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "veggieomlet",
        { name = "egg and egg >= 1 and veggie and veggie >= 1 and not meats and not dairy end,", id = 63, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "dairy", },
            },
            must_needs = {
                { atmost = 1000, atleast = 1, name = "veggie", },
                { atmost = 1000, atleast = 1, name = "egg", },
            },
        },
        priority = { cal = 10.9375, default = -1, },
        best_recipe = { cal = 26.5625,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 9.375, name = "bird_egg_cooked", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "butterflymuffin",
        { name = "(butterflywings or moonbutterflywings) and not meats and veggie and veggie >= 0.5 end,", id = 0,
            weight = 0, },
        needs = {
            or_needs = {
                {
                    { atleast = 0.01, atmost = 1000, cal = 9.375, name = "moonbutterflywings", },
                    { atleast = 0.01, atmost = 1000, cal = 9.375, name = "butterflywings", },
                },
            },
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.5, name = "veggie", },
            },
        },
        priority = { cal = 10.9375, default = -1, },
        best_recipe = { cal = 26.5625,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 9.375, name = "moonbutterflywings", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "bunnystew",
        { name = "(meats and meats < 1) and (frozen and frozen >= 2) and (not inedible) end,", id = 61, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "inedible", },
            },
            must_needs = {
                { atmost = 0.99, atleast = 0.01, name = "meats", },
                { atmost = 1000, atleast = 2, name = "frozen", },
            },
        },
        priority = { cal = 11.71875, default = -1, },
        best_recipe = { cal = 25.78125,
            slots = {
                { cal = 18.75, name = "monstermeat", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 56.25, name = "figatoni",
        { name = "(fig or fig_cooked) and veggie and veggie >= 2  and not meats end,", id = 58, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "fig", },
                { atmost = 1000, atleast = 2, name = "veggie", },
            },
        },
        priority = { cal = 16.40625, default = -1, },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 12.5, name = "fig", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "jammypreserves",
        { name = "fruit and not meats and not veggie and not inedible end,", id = 17, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "veggie", },
                { atmost = 0.01, atleast = 0, name = "inedible", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "fruit", },
            },
        },
        priority = { cal = 17.96875, default = -1, },
        best_recipe = { cal = 19.53125,
            slots = {
                { cal = 12.5, name = "cave_banana_cooked", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 25, name = "lobsterbisque",
        { name = "wobster_sheller_land and frozen end,", id = 45, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "frozen", },
                { atmost = 1000, atleast = 0.01, name = "wobster_sheller_land", },
            },
        },
        priority = { cal = 17.96875, default = -1, },
        best_recipe = { cal = 7.03125,
            slots = {
                { cal = 2.34375, name = "ice", },
                { name = "wobster_sheller_land", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 75, name = "baconeggs",
        { name = "egg and egg > 1 and meats and meats > 1 and not veggie end,", id = 11, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "veggie", },
            },
            must_needs = {
                { atmost = 1000, atleast = 1.01, name = "meats", },
                { atmost = 1000, atleast = 1.01, name = "egg", },
            },
        },
        priority = { cal = 18.75, default = -1, },
        best_recipe = { cal = 56.25,
            slots = {
                { cal = 18.75, name = "monstermeat", },
                { cal = 18.75, name = "monstermeat", },
                { cal = 9.375, name = "bird_egg_cooked", },
                { cal = 9.375, name = "bird_egg_cooked", },
            },
        },
    },
    { cal = 50, name = "justeggs",
        { name = "egg and egg >= 3 end,", id = 62, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 3, name = "egg", },
            },
        },
        priority = { cal = 19.53125, default = -1, },
        best_recipe = { cal = 30.46875,
            slots = {
                { cal = 9.375, name = "bird_egg_cooked", },
                { cal = 9.375, name = "bird_egg_cooked", },
                { cal = 9.375, name = "bird_egg_cooked", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "guacamole",
        { name = "mole and (rock_avocado_fruit_ripe or cactus_meat) and not fruit end,", id = 30, weight = 0, },
        needs = {
            or_needs = {
                {
                    { atleast = 0.01, atmost = 1000, cal = 12.5, name = "cactus_meat", },
                    { atleast = 0.01, atmost = 1000, cal = 12.5, name = "rock_avocado_fruit_ripe", },
                },
            },
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "fruit", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "mole", },
            },
        },
        priority = { cal = 20.3125, default = -1, },
        best_recipe = { cal = 17.1875,
            slots = {
                { name = "mole", },
                { cal = 12.5, name = "cactus_meat", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 37.5, name = "californiaroll",
        { name = "(kelp or 0 == 2 and (fish and fish >= 1) end,", id = 42, weight = 0, },
        needs = {
            or_needs = {
                {
                    { atleast = 0.01, atmost = 1000, cal = 9.375, name = "kelp", },
                    { atleast = 1, atmost = 1000, cal = 12.5, name = "fish", },
                    { atmost = 2, atleast = 2, name = "0", },
                },
            },
            not_tags = {},
            must_needs = {},
        },
        priority = { cal = 21.09375, default = -1, },
        best_recipe = { cal = 16.40625,
            slots = {
                { cal = 9.375, name = "kelp", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 75, name = "barnaclinguine",
        { name = "(barnacle >= 2 ) and veggie and veggie >= 2 end,", id = 49, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 2, name = "barnacle", },
                { atmost = 1000, atleast = 2, name = "veggie", },
            },
        },
        priority = { cal = 25.0, default = -1, },
        best_recipe = { cal = 50.0,
            slots = {
                { cal = 12.5, name = "barnacle", },
                { cal = 12.5, name = "barnacle", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
            },
        },
    },
    { cal = 75, name = "meatysalad",
        { name = "(plantmeat or plantmeat_cooked) and veggie and veggie >= 3 end,", id = 54, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "plantmeat", },
                { atmost = 1000, atleast = 3, name = "veggie", },
            },
        },
        priority = { cal = 25.0, default = -1, },
        best_recipe = { cal = 50.0,
            slots = {
                { cal = 12.5, name = "plantmeat", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
            },
        },
    },
    { cal = 75, name = "honeyham",
        { name = "honey and meats and meats > 1.5 and not inedible end,", id = 7, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "inedible", },
            },
            must_needs = {
                { atmost = 1000, atleast = 1.51, name = "meats", },
                { atmost = 1000, atleast = 0.01, name = "honey", },
            },
        },
        priority = { cal = 25.78125, default = -1, },
        best_recipe = { cal = 49.21875,
            slots = {
                { cal = 18.75, name = "monstermeat", },
                { cal = 18.75, name = "monstermeat", },
                { cal = 9.375, name = "honey", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 75, name = "barnaclestuffedfishhead",
        { name = "(barnacle or barnacle_cooked) and fish and fish >= 1.25 end,", id = 50, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "barnacle", },
                { atmost = 1000, atleast = 1.25, name = "fish", },
            },
        },
        priority = { cal = 35.15625, default = -1, },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 12.5, name = "barnacle", },
                { cal = 12.5, name = "fish", },
                { cal = 12.5, name = "fish", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 62.5, name = "meatballs",
        { name = "meats and not inedible end,", id = 12, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "inedible", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "meats", },
            },
        },
        priority = { cal = 36.71875, default = -1, },
        best_recipe = { cal = 25.78125,
            slots = {
                { cal = 18.75, name = "monstermeat", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 75, name = "turkeydinner",
        { name = "drumstick and drumstick > 1 and meats and meats > 1 and ((veggie and veggie >= 0.5) or fruit) end,",
            id = 15, weight = 0, },
        needs = {
            or_needs = {
                {
                    { atmost = 1000, atleast = 0.01, name = "fruit", },
                    { atmost = 1000, atleast = 0.5, name = "veggie", },
                },
            },
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 1.01, name = "drumstick", },
            },
        },
        priority = { cal = 45.3125, default = -1, },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 12.5, name = "drumstick", },
                { cal = 12.5, name = "drumstick", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 75, name = "dragonpie",
        { name = "(dragonfruit or dragonfruit_cooked) and not meats end,", id = 8, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "meats", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "dragonfruit", },
            },
        },
        priority = { cal = 58.59375, default = -1, },
        best_recipe = { cal = 16.40625,
            slots = {
                { cal = 9.375, name = "dragonfruit", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 150, name = "mandrakesoup",
        { name = "mandrake end,", id = 10, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "mandrake", },
            },
        },
        priority = { cal = 67.96875, default = -1, },
        best_recipe = { cal = 82.03125,
            slots = {
                { cal = 75, name = "mandrake", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 100, name = "beefalofeed",
        { name = "inedible and not monster and not meats and not fish and not egg and not fat and not dairy and not magic end,",
            id = 65, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "monster", },
                { atmost = 0.01, atleast = 0, name = "meats", },
                { atmost = 0.01, atleast = 0, name = "fish", },
                { atmost = 0.01, atleast = 0, name = "egg", },
                { atmost = 0.01, atleast = 0, name = "fat", },
                { atmost = 0.01, atleast = 0, name = "dairy", },
                { atmost = 0.01, atleast = 0, name = "magic", },
            },
            must_needs = {
                { atmost = 1000, atleast = 0.01, name = "inedible", },
            },
        },
        priority = { cal = 83.59375, default = -1, },
        best_recipe = { cal = 16.40625,
            slots = {
                { cal = 9.375, name = "twigs", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 150, name = "bonestew",
        { name = "meats and meats >= 3 and not inedible end,", id = 13, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {
                { atmost = 0.01, atleast = 0, name = "inedible", },
            },
            must_needs = {
                { atmost = 1000, atleast = 3, name = "meats", },
            },
        },
        priority = { cal = 91.40625, default = -1, },
        best_recipe = { cal = 58.59375,
            slots = {
                { cal = 18.75, name = "monstermeat", },
                { cal = 18.75, name = "monstermeat", },
                { cal = 18.75, name = "monstermeat", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
    { cal = 150, name = "talleggs",
        { name = "tallbirdegg and veggie and veggie >= 1 end,", id = 64, weight = 0, },
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { atmost = 1000, atleast = 1, name = "veggie", },
                { atmost = 1000, atleast = 0.01, name = "tallbirdegg", },
            },
        },
        priority = { cal = 107.8125, default = -1, },
        best_recipe = { cal = 42.1875,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe", },
                { cal = 25, name = "tallbirdegg", },
                { cal = 2.34375, name = "ice", },
                { cal = 2.34375, name = "ice", },
            },
        },
    },
}
return preparedfoods
