local preparedfoods = {
    { name = "powcake", cal = 0,
        { name = "twigs and honey and (corn or corn_cooked or oceanfish_small_5_inv or oceanfish_medium_5_inv) end,", id = 22, weight = 0,},
        priority = { default = -1, cal = -33.59375,},
        needs = {
            or_needs = {
                {
                    { name = "oceanfish_small_5_inv", cal = 12.5, atleast = 0.01, atmost = 1000,},
                    { name = "oceanfish_medium_5_inv", cal = 25, atleast = 0.01, atmost = 1000,},
                    { name = "corn", cal = 25, atleast = 0.01, atmost = 1000,},
                },
            },
            not_tags = {},
            must_needs = {
                { name = "honey", atleast = 0.01, atmost = 1000,},
                { name = "twigs", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 33.59375,
            slots = {
                { cal = 9.375, name = "honey",},
                { cal = 9.375, name = "twigs",},
                { cal = 12.5, name = "oceanfish_small_5_inv",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "asparagussoup", cal = 18.75,
        { name = "(asparagus or asparagus_cooked) and veggie and veggie > 2 and not meats and not inedible end,", id = 34, weight = 0,},
        priority = { default = -1, cal = -31.25,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "inedible", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "asparagus", atleast = 0.01, atmost = 1000,},
                { name = "veggie", atleast = 2.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 50.0,
            slots = {
                { cal = 12.5, name = "asparagus",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
            },
        },
    },
    { name = "trailmix", cal = 12.5,
        { name = "(acorn or acorn_cooked) and seed and seed >= 1 and (berries or berries_cooked or berries_juicy or berries_juicy_cooked) and fruit and fruit >= 1 and not meats and not veggie and not egg and not dairy end,", id = 28, weight = 0,},
        priority = { default = -1, cal = -28.125,},
        needs = {
            or_needs = {
                {
                    { name = "berries", cal = 9.375, atleast = 0.01, atmost = 1000,},
                    { name = "berries_juicy", cal = 12.5, atleast = 0.01, atmost = 1000,},
                },
            },
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "veggie", atleast = 0, atmost = 0.01,},
                { name = "egg", atleast = 0, atmost = 0.01,},
                { name = "dairy", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "acorn", atleast = 0.01, atmost = 1000,},
                { name = "fruit", atleast = 1, atmost = 1000,},
                { name = "seed", atleast = 1, atmost = 1000,},
            },
        },
        best_recipe = { cal = 40.625,
            slots = {
                { cal = 9.375, name = "acorn",},
                { cal = 12.5, name = "cave_banana_cooked",},
                { cal = 9.375, name = "acorn",},
                { cal = 9.375, name = "berries",},
            },
        },
    },
    { name = "flowersalad", cal = 12.5,
        { name = "cactus_flower and veggie and veggie >= 2 and not meats and not inedible and not egg and not sweetener and not fruit end,", id = 25, weight = 0,},
        priority = { default = -1, cal = -27.34375,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "inedible", atleast = 0, atmost = 0.01,},
                { name = "egg", atleast = 0, atmost = 0.01,},
                { name = "sweetener", atleast = 0, atmost = 0.01,},
                { name = "fruit", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "veggie", atleast = 2, atmost = 1000,},
                { name = "cactus_flower", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 12.5, name = "cactus_flower",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "shroomcake", cal = 25,
        { name = "moon_cap and red_cap and blue_cap and green_cap end,", id = 55, weight = 0,},
        priority = { default = -1, cal = -25.0,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "green_cap", atleast = 0.01, atmost = 1000,},
                { name = "blue_cap", atleast = 0.01, atmost = 1000,},
                { name = "red_cap", atleast = 0.01, atmost = 1000,},
                { name = "moon_cap", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 50.0,
            slots = {
                { cal = 12.5, name = "green_cap",},
                { cal = 12.5, name = "blue_cap",},
                { cal = 12.5, name = "red_cap",},
                { cal = 12.5, name = "moon_cap",},
            },
        },
    },
    { name = "hotchili", cal = 37.5,
        { name = "meats and meats >= 1.5 and veggie and veggie >= 1.5 end,", id = 29, weight = 0,},
        priority = { default = -1, cal = -25.0,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "veggie", atleast = 1.5, atmost = 1000,},
                { name = "meats", atleast = 1.5, atmost = 1000,},
            },
        },
        best_recipe = { cal = 62.5,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 18.75, name = "monstermeat",},
                { cal = 18.75, name = "monstermeat",},
            },
        },
    },
    { name = "pumpkincookie", cal = 37.5,
        { name = "(pumpkin or pumpkin_cooked) and sweetener and sweetener >= 2 end,", id = 3, weight = 0,},
        priority = { default = -1, cal = -21.09375,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "pumpkin", atleast = 0.01, atmost = 1000,},
                { name = "sweetener", atleast = 2, atmost = 1000,},
            },
        },
        best_recipe = { cal = 58.59375,
            slots = {
                { cal = 37.5, name = "pumpkin",},
                { cal = 9.375, name = "honey",},
                { cal = 9.375, name = "honey",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "jellybean", cal = 0,
        { name = "royal_jelly and not inedible and not monster end,", id = 31, weight = 0,},
        priority = { default = -1, cal = -19.53125,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "inedible", atleast = 0, atmost = 0.01,},
                { name = "monster", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "royal_jelly", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 19.53125,
            slots = {
                { cal = 12.5, name = "royal_jelly",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "lobsterdinner", cal = 37.5,
        { name = "wobster_sheller_land and butter and (meats and meats >= 1.0) and (fish and fish >= 1.0) and not frozen end,", id = 46, weight = 0,},
        priority = { default = -1, cal = -18.75,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "frozen", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "meats", atleast = 1, atmost = 1000,},
                { name = "fish", atleast = 1, atmost = 1000,},
                { name = "butter", atleast = 0.01, atmost = 1000,},
                { name = "wobster_sheller_land", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 56.25,
            slots = {
                { cal = 18.75, name = "monstermeat",},
                { cal = 12.5, name = "fish",},
                { cal = 25, name = "butter",},
                { name = "wobster_sheller_land",},
            },
        },
    },
    { name = "figkabab", cal = 25,
        { name = "(fig or fig_cooked) and twigs and meats and meats >= 1 and (not monster or monster <= 1) end,", id = 59, weight = 0,},
        priority = { default = -1, cal = -17.96875,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "monster", atleast = 0.01, atmost = 1,},
            },
            must_needs = {
                { name = "fig", atleast = 0.01, atmost = 1000,},
                { name = "meats", atleast = 1, atmost = 1000,},
                { name = "twigs", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 42.96875,
            slots = {
                { cal = 12.5, name = "fig",},
                { cal = 18.75, name = "monstermeat",},
                { cal = 9.375, name = "twigs",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "vegstinger", cal = 25,
        { name = "(asparagus or asparagus_cooked or tomato or tomato_cooked) and veggie and veggie > 2 and frozen and not meats and not inedible and not egg end,", id = 35, weight = 0,},
        priority = { default = -1, cal = -14.84375,},
        needs = {
            or_needs = {
                {
                    { name = "tomato", atleast = 0.01, atmost = 1000,},
                    { name = "asparagus", atleast = 0.01, atmost = 1000,},
                },
            },
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "inedible", atleast = 0, atmost = 0.01,},
                { name = "egg", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "frozen", atleast = 0.01, atmost = 1000,},
                { name = "veggie", atleast = 2.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 2.34375, name = "ice",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
            },
        },
    },
    { name = "fruitmedley", cal = 25,
        { name = "fruit and fruit >= 3 and not meats and not veggie end,", id = 18, weight = 0,},
        priority = { default = -1, cal = -14.84375,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "veggie", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "fruit", atleast = 3, atmost = 1000,},
            },
        },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 12.5, name = "cave_banana_cooked",},
                { cal = 12.5, name = "cave_banana_cooked",},
                { cal = 12.5, name = "cave_banana_cooked",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "stuffedeggplant", cal = 37.5,
        { name = "(eggplant or eggplant_cooked) and veggie and veggie > 1 end,", id = 4, weight = 0,},
        priority = { default = -1, cal = -14.84375,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "eggplant", atleast = 0.01, atmost = 1000,},
                { name = "veggie", atleast = 1.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 52.34375,
            slots = {
                { cal = 25, name = "eggplant",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "sweettea", cal = 0,
        { name = "forgetmelots and sweetener and frozen and not monster and not veggie and not meats and not fish and not egg and not fat and not dairy and not inedible end,", id = 56, weight = 0,},
        priority = { default = -1, cal = -14.0625,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "monster", atleast = 0, atmost = 0.01,},
                { name = "veggie", atleast = 0, atmost = 0.01,},
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "fish", atleast = 0, atmost = 0.01,},
                { name = "egg", atleast = 0, atmost = 0.01,},
                { name = "fat", atleast = 0, atmost = 0.01,},
                { name = "dairy", atleast = 0, atmost = 0.01,},
                { name = "inedible", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "frozen", atleast = 0.01, atmost = 1000,},
                { name = "sweetener", atleast = 0.01, atmost = 1000,},
                { name = "forgetmelots", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 14.0625,
            slots = {
                { cal = 2.34375, name = "ice",},
                { cal = 9.375, name = "honey",},
                { cal = 0, name = "forgetmelots",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "watermelonicle", cal = 12.5,
        { name = "watermelon and frozen and twigs and not meats and not veggie and not egg end,", id = 27, weight = 0,},
        priority = { default = -1, cal = -14.0625,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "veggie", atleast = 0, atmost = 0.01,},
                { name = "egg", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "twigs", atleast = 0.01, atmost = 1000,},
                { name = "frozen", atleast = 0.01, atmost = 1000,},
                { name = "watermelon", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 26.5625,
            slots = {
                { cal = 9.375, name = "twigs",},
                { cal = 2.34375, name = "ice",},
                { cal = 12.5, name = "watermelon",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "bananapop", cal = 12.5,
        { name = "(cave_banana or cave_banana_cooked) and frozen and twigs and not meats and not fish end,", id = 36, weight = 0,},
        priority = { default = -1, cal = -14.0625,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "fish", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "cave_banana", atleast = 0.01, atmost = 1000,},
                { name = "twigs", atleast = 0.01, atmost = 1000,},
                { name = "frozen", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 26.5625,
            slots = {
                { cal = 12.5, name = "cave_banana",},
                { cal = 9.375, name = "twigs",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "frognewton", cal = 18.75,
        { name = "(fig or fig_cooked) and (froglegs or froglegs_cooked) end,", id = 60, weight = 0,},
        priority = { default = -1, cal = -10.9375,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "fig", atleast = 0.01, atmost = 1000,},
                { name = "froglegs", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 12.5, name = "fig",},
                { cal = 12.5, name = "froglegs",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "leafymeatburger", cal = 37.5,
        { name = "(plantmeat or plantmeat_cooked) and (onion or onion_cooked) and veggie and veggie >= 2 end,", id = 52, weight = 0,},
        priority = { default = -1, cal = -9.375,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "plantmeat", atleast = 0.01, atmost = 1000,},
                { name = "onion", atleast = 0.01, atmost = 1000,},
                { name = "veggie", atleast = 2, atmost = 1000,},
            },
        },
        best_recipe = { cal = 46.875,
            slots = {
                { cal = 12.5, name = "plantmeat",},
                { cal = 9.375, name = "onion",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
            },
        },
    },
    { name = "wetgoop", cal = 0,
        { name = "true end,", id = 24, weight = 0,},
        priority = { default = -1, cal = -9.375,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "true", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 9.375,
            slots = {
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "waffles", cal = 37.5,
        { name = "butter and (berries or berries_cooked or berries_juicy or berries_juicy_cooked) and egg end,", id = 20, weight = 0,},
        priority = { default = -1, cal = -8.59375,},
        needs = {
            or_needs = {
                {
                    { name = "berries", cal = 9.375, atleast = 0.01, atmost = 1000,},
                    { name = "berries_juicy", cal = 12.5, atleast = 0.01, atmost = 1000,},
                },
            },
            not_tags = {},
            must_needs = {
                { name = "egg", atleast = 0.01, atmost = 1000,},
                { name = "butter", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 46.09375,
            slots = {
                { cal = 9.375, name = "bird_egg_cooked",},
                { cal = 25, name = "butter",},
                { cal = 9.375, name = "berries",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "pepperpopper", cal = 25,
        { name = "(pepper or pepper_cooked) and meats and meats <= 1.5 and not inedible end,", id = 41, weight = 0,},
        priority = { default = -1, cal = -7.8125,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "inedible", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "pepper", atleast = 0.01, atmost = 1000,},
                { name = "meats", atleast = 0.01, atmost = 1.5,},
            },
        },
        best_recipe = { cal = 32.8125,
            slots = {
                { cal = 9.375, name = "pepper",},
                { cal = 18.75, name = "monstermeat",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "leafymeatsouffle", cal = 37.5,
        { name = "(plantmeat >= 2 ) and sweetener and sweetener >= 2 end,", id = 53, weight = 0,},
        priority = { default = -1, cal = -6.25,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "plantmeat", atleast = 2, atmost = 1000,},
                { name = "sweetener", atleast = 2, atmost = 1000,},
            },
        },
        best_recipe = { cal = 43.75,
            slots = {
                { cal = 12.5, name = "plantmeat",},
                { cal = 12.5, name = "plantmeat",},
                { cal = 9.375, name = "honey",},
                { cal = 9.375, name = "honey",},
            },
        },
    },
    { name = "surfnturf", cal = 37.5,
        { name = "meats and meats >= 2.5 and fish and fish >= 1.5 and not frozen end,", id = 44, weight = 0,},
        priority = { default = -1, cal = -6.25,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "frozen", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "fish", atleast = 1.5, atmost = 1000,},
                { name = "meats", atleast = 2.5, atmost = 1000,},
            },
        },
        best_recipe = { cal = 43.75,
            slots = {
                { cal = 12.5, name = "fish",},
                { cal = 12.5, name = "fish",},
                { cal = 9.375, name = "twigs",},
                { cal = 9.375, name = "twigs",},
            },
        },
    },
    { name = "perogies", cal = 37.5,
        { name = "egg and meats and veggie and veggie >= 0.5 and not inedible end,", id = 14, weight = 0,},
        priority = { default = -1, cal = -5.46875,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "inedible", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "veggie", atleast = 0.5, atmost = 1000,},
                { name = "meats", atleast = 0.01, atmost = 1000,},
                { name = "egg", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 42.96875,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 18.75, name = "monstermeat",},
                { cal = 9.375, name = "bird_egg_cooked",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "taffy", cal = 25,
        { name = "sweetener and sweetener >= 3 and not meats end,", id = 2, weight = 0,},
        priority = { default = -1, cal = -5.46875,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "sweetener", atleast = 3, atmost = 1000,},
            },
        },
        best_recipe = { cal = 30.46875,
            slots = {
                { cal = 9.375, name = "honey",},
                { cal = 9.375, name = "honey",},
                { cal = 9.375, name = "honey",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "monsterlasagna", cal = 37.5,
        { name = "monster and monster >= 2 and not inedible end,", id = 21, weight = 0,},
        priority = { default = -1, cal = -4.6875,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "inedible", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "monster", atleast = 2, atmost = 1000,},
            },
        },
        best_recipe = { cal = 42.1875,
            slots = {
                { cal = 18.75, name = "cookedmonstermeat",},
                { cal = 18.75, name = "cookedmonstermeat",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "unagi", cal = 18.75,
        { name = "(cutlichen or kelp or kelp_cooked or kelp_dried) and (eel or eel_cooked or pondeel) end,", id = 23, weight = 0,},
        priority = { default = -1, cal = -4.6875,},
        needs = {
            or_needs = {
                {
                    { name = "kelp_dried", cal = 9.375, atleast = 0.01, atmost = 1000,},
                    { name = "kelp", cal = 9.375, atleast = 0.01, atmost = 1000,},
                    { name = "cutlichen", cal = 12.5, atleast = 0.01, atmost = 1000,},
                },
                {
                    { name = "pondeel", cal = 9.375, atleast = 0.01, atmost = 1000,},
                    { name = "eel", cal = 9.375, atleast = 0.01, atmost = 1000,},
                },
            },
            not_tags = {},
            must_needs = {},
        },
        best_recipe = { cal = 23.4375,
            slots = {
                { cal = 9.375, name = "kelp_dried",},
                { cal = 9.375, name = "pondeel",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "ceviche", cal = 25,
        { name = "fish and fish >= 2 and frozen and not inedible and not egg end,", id = 39, weight = 0,},
        priority = { default = -1, cal = -4.6875,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "inedible", atleast = 0, atmost = 0.01,},
                { name = "egg", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "frozen", atleast = 0.01, atmost = 1000,},
                { name = "fish", atleast = 2, atmost = 1000,},
            },
        },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 2.34375, name = "ice",},
                { cal = 12.5, name = "fish",},
                { cal = 12.5, name = "fish",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "bananajuice", cal = 25,
        { name = "(cave_banana >= 2) and not meats and not fish and not monster end,", id = 38, weight = 0,},
        priority = { default = -1, cal = -4.6875,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "fish", atleast = 0, atmost = 0.01,},
                { name = "monster", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "cave_banana", atleast = 2, atmost = 1000,},
            },
        },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 12.5, name = "cave_banana",},
                { cal = 12.5, name = "cave_banana",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "kabobs", cal = 37.5,
        { name = "meats and twigs and (not monster or monster <= 1) and (inedible and inedible <= 1) end,", id = 9, weight = 0,},
        priority = { default = -1, cal = -2.34375,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "monster", atleast = 0.01, atmost = 1,},
            },
            must_needs = {
                { name = "inedible", atleast = 0.01, atmost = 1,},
                { name = "twigs", atleast = 0.01, atmost = 1000,},
                { name = "meats", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 9.375, name = "twigs",},
                { cal = 9.375, name = "twigs",},
                { cal = 18.75, name = "monstermeat",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "seafoodgumbo", cal = 37.5,
        { name = "fish and fish > 2 end,", id = 43, weight = 0,},
        priority = { default = -1, cal = -2.34375,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "fish", atleast = 2.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 12.5, name = "fish",},
                { cal = 12.5, name = "fish",},
                { cal = 12.5, name = "fish",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "salsa", cal = 25,
        { name = "(tomato or tomato_cooked) and (onion or onion_cooked) and not meats and not inedible and not egg end,", id = 40, weight = 0,},
        priority = { default = -1, cal = -1.5625,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "inedible", atleast = 0, atmost = 0.01,},
                { name = "egg", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "tomato", atleast = 0.01, atmost = 1000,},
                { name = "onion", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 26.5625,
            slots = {
                { cal = 12.5, name = "tomato",},
                { cal = 9.375, name = "onion",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "icecream", cal = 25,
        { name = "frozen and dairy and sweetener and not meats and not veggie and not inedible and not egg end,", id = 26, weight = 0,},
        priority = { default = -1, cal = -1.5625,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "veggie", atleast = 0, atmost = 0.01,},
                { name = "inedible", atleast = 0, atmost = 0.01,},
                { name = "egg", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "sweetener", atleast = 0.01, atmost = 1000,},
                { name = "dairy", atleast = 0.01, atmost = 1000,},
                { name = "frozen", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 26.5625,
            slots = {
                { cal = 9.375, name = "honey",},
                { cal = 12.5, name = "milkywhites",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "frozenbananadaiquiri", cal = 18.75,
        { name = "(cave_banana or cave_banana_cooked) and (frozen and frozen >= 1) and not meats and not fish end,", id = 37, weight = 0,},
        priority = { default = -1, cal = -0.78125,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "fish", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "cave_banana", atleast = 0.01, atmost = 1000,},
                { name = "frozen", atleast = 1, atmost = 1000,},
            },
        },
        best_recipe = { cal = 19.53125,
            slots = {
                { cal = 12.5, name = "cave_banana",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "mashedpotatoes", cal = 37.5,
        { name = "((potato and potato > 1) or (potato_cooked and potato_cooked > 1) or (potato and potato_cooked)) and (garlic or garlic_cooked) and not meats and not inedible end,", id = 33, weight = 0,},
        priority = { default = -1, cal = 0.78125,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "inedible", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "potato", atleast = 1.01, atmost = 1000,},
                { name = "garlic", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 36.71875,
            slots = {
                { cal = 12.5, name = "potato",},
                { cal = 12.5, name = "potato",},
                { cal = 9.375, name = "garlic",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "koalefig_trunk", cal = 56.25,
        { name = "(trunk_summer or trunk_cooked or trunk_winter) and (fig or fig_cooked) end,", id = 57, weight = 0,},
        priority = { default = -1, cal = 1.5625,},
        needs = {
            or_needs = {
                {
                    { name = "trunk_winter", cal = 37.5, atleast = 0.01, atmost = 1000,},
                    { name = "trunk_summer", cal = 37.5, atleast = 0.01, atmost = 1000,},
                    { name = "trunk_cooked", cal = 75, atleast = 0.01, atmost = 1000,},
                },
            },
            not_tags = {},
            must_needs = {
                { name = "fig", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 54.6875,
            slots = {
                { cal = 12.5, name = "fig",},
                { cal = 37.5, name = "trunk_winter",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "fishsticks", cal = 37.5,
        { name = "fish and twigs and (inedible and inedible <= 1) end,", id = 5, weight = 0,},
        priority = { default = -1, cal = 3.90625,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "inedible", atleast = 0.01, atmost = 1,},
                { name = "twigs", atleast = 0.01, atmost = 1000,},
                { name = "fish", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 33.59375,
            slots = {
                { cal = 9.375, name = "twigs",},
                { cal = 9.375, name = "twigs",},
                { cal = 12.5, name = "fish",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "barnaclesushi", cal = 37.5,
        { name = "(barnacle or barnacle_cooked) and (kelp or kelp_cooked) and egg and egg >= 1 end,", id = 48, weight = 0,},
        priority = { default = -1, cal = 3.90625,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "barnacle", atleast = 0.01, atmost = 1000,},
                { name = "kelp", atleast = 0.01, atmost = 1000,},
                { name = "egg", atleast = 1, atmost = 1000,},
            },
        },
        best_recipe = { cal = 33.59375,
            slots = {
                { cal = 12.5, name = "barnacle",},
                { cal = 9.375, name = "kelp",},
                { cal = 9.375, name = "bird_egg_cooked",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "potatotornado", cal = 37.5,
        { name = "(potato or potato_cooked) and twigs and (not monster or monster <= 1) and not meats and (inedible and inedible <= 2) end,", id = 32, weight = 0,},
        priority = { default = -1, cal = 3.90625,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "monster", atleast = 0.01, atmost = 1,},
                { name = "meats", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "potato", atleast = 0.01, atmost = 1000,},
                { name = "inedible", atleast = 0.01, atmost = 2,},
                { name = "twigs", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 33.59375,
            slots = {
                { cal = 12.5, name = "potato",},
                { cal = 9.375, name = "twigs",},
                { cal = 9.375, name = "twigs",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "beefalotreat", cal = 25,
        { name = "inedible and seed and forgetmelots and not monster and not meats and not fish and not egg and not fat and not dairy and not magic end,", id = 66, weight = 0,},
        priority = { default = -1, cal = 3.90625,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "monster", atleast = 0, atmost = 0.01,},
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "fish", atleast = 0, atmost = 0.01,},
                { name = "egg", atleast = 0, atmost = 0.01,},
                { name = "fat", atleast = 0, atmost = 0.01,},
                { name = "dairy", atleast = 0, atmost = 0.01,},
                { name = "magic", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "forgetmelots", atleast = 0.01, atmost = 1000,},
                { name = "seed", atleast = 0.01, atmost = 1000,},
                { name = "inedible", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 21.09375,
            slots = {
                { cal = 0, name = "forgetmelots",},
                { cal = 9.375, name = "acorn",},
                { cal = 9.375, name = "twigs",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "honeynuggets", cal = 37.5,
        { name = "honey and meats and meats <= 1.5 and not inedible end,", id = 6, weight = 0,},
        priority = { default = -1, cal = 4.6875,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "inedible", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "meats", atleast = 0.01, atmost = 1.5,},
                { name = "honey", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 32.8125,
            slots = {
                { cal = 18.75, name = "monstermeat",},
                { cal = 9.375, name = "honey",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "ratatouille", cal = 25,
        { name = "not meats and veggie and veggie >= 0.5 and not inedible end,", id = 16, weight = 0,},
        priority = { default = -1, cal = 5.46875,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "inedible", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "veggie", atleast = 0.5, atmost = 1000,},
            },
        },
        best_recipe = { cal = 19.53125,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "fishtacos", cal = 37.5,
        { name = "fish and (corn or corn_cooked or oceanfish_small_5_inv or oceanfish_medium_5_inv) end,", id = 19, weight = 0,},
        priority = { default = -1, cal = 7.8125,},
        needs = {
            or_needs = {
                {
                    { name = "oceanfish_small_5_inv", cal = 12.5, atleast = 0.01, atmost = 1000,},
                    { name = "oceanfish_medium_5_inv", cal = 25, atleast = 0.01, atmost = 1000,},
                    { name = "corn", cal = 25, atleast = 0.01, atmost = 1000,},
                },
            },
            not_tags = {},
            must_needs = {
                { name = "fish", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 12.5, name = "fish",},
                { cal = 12.5, name = "oceanfish_small_5_inv",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "leafloaf", cal = 37.5,
        { name = "(plantmeat >= 2 ) end,", id = 51, weight = 0,},
        priority = { default = -1, cal = 7.8125,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "plantmeat", atleast = 2, atmost = 1000,},
            },
        },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 12.5, name = "plantmeat",},
                { cal = 12.5, name = "plantmeat",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "barnaclepita", cal = 37.5,
        { name = "(barnacle or barnacle_cooked) and veggie and veggie >= 0.5 end,", id = 47, weight = 0,},
        priority = { default = -1, cal = 7.8125,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "barnacle", atleast = 0.01, atmost = 1000,},
                { name = "veggie", atleast = 0.5, atmost = 1000,},
            },
        },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 12.5, name = "barnacle",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "frogglebunwich", cal = 37.5,
        { name = "(froglegs or froglegs_cooked) and veggie and veggie >= 0.5 end,", id = 1, weight = 0,},
        priority = { default = -1, cal = 7.8125,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "froglegs", atleast = 0.01, atmost = 1000,},
                { name = "veggie", atleast = 0.5, atmost = 1000,},
            },
        },
        best_recipe = { cal = 29.6875,
            slots = {
                { cal = 12.5, name = "froglegs",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "veggieomlet", cal = 37.5,
        { name = "egg and egg >= 1 and veggie and veggie >= 1 and not meats and not dairy end,", id = 63, weight = 0,},
        priority = { default = -1, cal = 10.9375,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "dairy", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "veggie", atleast = 1, atmost = 1000,},
                { name = "egg", atleast = 1, atmost = 1000,},
            },
        },
        best_recipe = { cal = 26.5625,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 9.375, name = "bird_egg_cooked",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "butterflymuffin", cal = 37.5,
        { name = "(butterflywings or moonbutterflywings) and not meats and veggie and veggie >= 0.5 end,", id = 0, weight = 0,},
        priority = { default = -1, cal = 10.9375,},
        needs = {
            or_needs = {
                {
                    { name = "moonbutterflywings", cal = 9.375, atleast = 0.01, atmost = 1000,},
                    { name = "butterflywings", cal = 9.375, atleast = 0.01, atmost = 1000,},
                },
            },
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "veggie", atleast = 0.5, atmost = 1000,},
            },
        },
        best_recipe = { cal = 26.5625,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 9.375, name = "moonbutterflywings",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "bunnystew", cal = 37.5,
        { name = "(meats and meats < 1) and (frozen and frozen >= 2) and (not inedible) end,", id = 61, weight = 0,},
        priority = { default = -1, cal = 11.71875,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "inedible", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "meats", atleast = 0.01, atmost = 0.99,},
                { name = "frozen", atleast = 2, atmost = 1000,},
            },
        },
        best_recipe = { cal = 25.78125,
            slots = {
                { cal = 18.75, name = "monstermeat",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "figatoni", cal = 56.25,
        { name = "(fig or fig_cooked) and veggie and veggie >= 2  and not meats end,", id = 58, weight = 0,},
        priority = { default = -1, cal = 16.40625,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "fig", atleast = 0.01, atmost = 1000,},
                { name = "veggie", atleast = 2, atmost = 1000,},
            },
        },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 12.5, name = "fig",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "jammypreserves", cal = 37.5,
        { name = "fruit and not meats and not veggie and not inedible end,", id = 17, weight = 0,},
        priority = { default = -1, cal = 17.96875,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "veggie", atleast = 0, atmost = 0.01,},
                { name = "inedible", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "fruit", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 19.53125,
            slots = {
                { cal = 12.5, name = "cave_banana_cooked",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "lobsterbisque", cal = 25,
        { name = "wobster_sheller_land and frozen end,", id = 45, weight = 0,},
        priority = { default = -1, cal = 17.96875,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "frozen", atleast = 0.01, atmost = 1000,},
                { name = "wobster_sheller_land", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 7.03125,
            slots = {
                { cal = 2.34375, name = "ice",},
                { name = "wobster_sheller_land",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "baconeggs", cal = 75,
        { name = "egg and egg > 1 and meats and meats > 1 and not veggie end,", id = 11, weight = 0,},
        priority = { default = -1, cal = 18.75,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "veggie", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "meats", atleast = 1.01, atmost = 1000,},
                { name = "egg", atleast = 1.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 56.25,
            slots = {
                { cal = 18.75, name = "monstermeat",},
                { cal = 18.75, name = "monstermeat",},
                { cal = 9.375, name = "bird_egg_cooked",},
                { cal = 9.375, name = "bird_egg_cooked",},
            },
        },
    },
    { name = "justeggs", cal = 50,
        { name = "egg and egg >= 3 end,", id = 62, weight = 0,},
        priority = { default = -1, cal = 19.53125,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "egg", atleast = 3, atmost = 1000,},
            },
        },
        best_recipe = { cal = 30.46875,
            slots = {
                { cal = 9.375, name = "bird_egg_cooked",},
                { cal = 9.375, name = "bird_egg_cooked",},
                { cal = 9.375, name = "bird_egg_cooked",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "guacamole", cal = 37.5,
        { name = "mole and (rock_avocado_fruit_ripe or cactus_meat) and not fruit end,", id = 30, weight = 0,},
        priority = { default = -1, cal = 20.3125,},
        needs = {
            or_needs = {
                {
                    { name = "cactus_meat", cal = 12.5, atleast = 0.01, atmost = 1000,},
                    { name = "rock_avocado_fruit_ripe", cal = 12.5, atleast = 0.01, atmost = 1000,},
                },
            },
            not_tags = {
                { name = "fruit", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "mole", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 17.1875,
            slots = {
                { name = "mole",},
                { cal = 12.5, name = "cactus_meat",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "californiaroll", cal = 37.5,
        { name = "(kelp or 0 == 2 and (fish and fish >= 1) end,", id = 42, weight = 0,},
        priority = { default = -1, cal = 21.09375,},
        needs = {
            or_needs = {
                {
                    { name = "kelp", cal = 9.375, atleast = 0.01, atmost = 1000,},
                    { name = "fish", cal = 12.5, atleast = 1, atmost = 1000,},
                    { name = "0", atleast = 2, atmost = 2,},
                },
            },
            not_tags = {},
            must_needs = {},
        },
        best_recipe = { cal = 16.40625,
            slots = {
                { cal = 9.375, name = "kelp",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "barnaclinguine", cal = 75,
        { name = "(barnacle >= 2 ) and veggie and veggie >= 2 end,", id = 49, weight = 0,},
        priority = { default = -1, cal = 25.0,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "barnacle", atleast = 2, atmost = 1000,},
                { name = "veggie", atleast = 2, atmost = 1000,},
            },
        },
        best_recipe = { cal = 50.0,
            slots = {
                { cal = 12.5, name = "barnacle",},
                { cal = 12.5, name = "barnacle",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
            },
        },
    },
    { name = "meatysalad", cal = 75,
        { name = "(plantmeat or plantmeat_cooked) and veggie and veggie >= 3 end,", id = 54, weight = 0,},
        priority = { default = -1, cal = 25.0,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "plantmeat", atleast = 0.01, atmost = 1000,},
                { name = "veggie", atleast = 3, atmost = 1000,},
            },
        },
        best_recipe = { cal = 50.0,
            slots = {
                { cal = 12.5, name = "plantmeat",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
            },
        },
    },
    { name = "honeyham", cal = 75,
        { name = "honey and meats and meats > 1.5 and not inedible end,", id = 7, weight = 0,},
        priority = { default = -1, cal = 25.78125,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "inedible", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "meats", atleast = 1.51, atmost = 1000,},
                { name = "honey", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 49.21875,
            slots = {
                { cal = 18.75, name = "monstermeat",},
                { cal = 18.75, name = "monstermeat",},
                { cal = 9.375, name = "honey",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "turkeydinner", cal = 75,
        { name = "drumstick and drumstick > 1 and meats and meats > 1 and ((veggie and veggie >= 0.5) or fruit) end,", id = 15, weight = 0,},
        priority = { default = -1, cal = 28.90625,},
        needs = {
            or_needs = {
                {
                    { name = "fruit", atleast = 0.01, atmost = 1000,},
                    { name = "veggie", atleast = 0.5, atmost = 1000,},
                },
            },
            not_tags = {},
            must_needs = {
                { name = "drumstick", atleast = 1.01, atmost = 1000,},
                { name = "meats", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 46.09375,
            slots = {
                { cal = 12.5, name = "drumstick",},
                { cal = 12.5, name = "drumstick",},
                { cal = 18.75, name = "monstermeat",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "barnaclestuffedfishhead", cal = 75,
        { name = "(barnacle or barnacle_cooked) and fish and fish >= 1.25 end,", id = 50, weight = 0,},
        priority = { default = -1, cal = 35.15625,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "barnacle", atleast = 0.01, atmost = 1000,},
                { name = "fish", atleast = 1.25, atmost = 1000,},
            },
        },
        best_recipe = { cal = 39.84375,
            slots = {
                { cal = 12.5, name = "barnacle",},
                { cal = 12.5, name = "fish",},
                { cal = 12.5, name = "fish",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "meatballs", cal = 62.5,
        { name = "meats and not inedible end,", id = 12, weight = 0,},
        priority = { default = -1, cal = 36.71875,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "inedible", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "meats", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 25.78125,
            slots = {
                { cal = 18.75, name = "monstermeat",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "dragonpie", cal = 75,
        { name = "(dragonfruit or dragonfruit_cooked) and not meats end,", id = 8, weight = 0,},
        priority = { default = -1, cal = 58.59375,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "meats", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "dragonfruit", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 16.40625,
            slots = {
                { cal = 9.375, name = "dragonfruit",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "mandrakesoup", cal = 150,
        { name = "mandrake end,", id = 10, weight = 0,},
        priority = { default = -1, cal = 67.96875,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "mandrake", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 82.03125,
            slots = {
                { cal = 75, name = "mandrake",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "beefalofeed", cal = 100,
        { name = "inedible and not monster and not meats and not fish and not egg and not fat and not dairy and not magic end,", id = 65, weight = 0,},
        priority = { default = -1, cal = 83.59375,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "monster", atleast = 0, atmost = 0.01,},
                { name = "meats", atleast = 0, atmost = 0.01,},
                { name = "fish", atleast = 0, atmost = 0.01,},
                { name = "egg", atleast = 0, atmost = 0.01,},
                { name = "fat", atleast = 0, atmost = 0.01,},
                { name = "dairy", atleast = 0, atmost = 0.01,},
                { name = "magic", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "inedible", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 16.40625,
            slots = {
                { cal = 9.375, name = "twigs",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "bonestew", cal = 150,
        { name = "meats and meats >= 3 and not inedible end,", id = 13, weight = 0,},
        priority = { default = -1, cal = 91.40625,},
        needs = {
            or_needs = {},
            not_tags = {
                { name = "inedible", atleast = 0, atmost = 0.01,},
            },
            must_needs = {
                { name = "meats", atleast = 3, atmost = 1000,},
            },
        },
        best_recipe = { cal = 58.59375,
            slots = {
                { cal = 18.75, name = "monstermeat",},
                { cal = 18.75, name = "monstermeat",},
                { cal = 18.75, name = "monstermeat",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
    { name = "talleggs", cal = 150,
        { name = "tallbirdegg and veggie and veggie >= 1 end,", id = 64, weight = 0,},
        priority = { default = -1, cal = 107.8125,},
        needs = {
            or_needs = {},
            not_tags = {},
            must_needs = {
                { name = "veggie", atleast = 1, atmost = 1000,},
                { name = "tallbirdegg", atleast = 0.01, atmost = 1000,},
            },
        },
        best_recipe = { cal = 42.1875,
            slots = {
                { cal = 12.5, name = "rock_avocado_fruit_ripe",},
                { cal = 25, name = "tallbirdegg",},
                { cal = 2.34375, name = "ice",},
                { cal = 2.34375, name = "ice",},
            },
        },
    },
}
return preparedfoods