local tags = {
    egg = {
        { cal = 25, tag = 4, name = "tallbirdegg_cooked", weight = 6.25,},
        { cal = 25, tag = 4, name = "tallbirdegg", weight = 6.25,},
        { cal = 9.375, tag = 1, name = "bird_egg", weight = 9.375,},
        { cal = 9.375, tag = 1, name = "bird_egg_cooked", weight = 9.375,},
        { name = "egg",},
    },
    decoration = {
        { cal = 0, tag = 1, name = "forgetmelots", weight = 0.0,},
        { cal = 1, tag = 2, name = "refined_dust", weight = 0.5,},
        { cal = 9.375, tag = 2, name = "moonbutterflywings", weight = 4.6875,},
        { cal = 9.375, tag = 2, name = "butterflywings", weight = 4.6875,},
        { name = "decoration",},
    },
    dairy = {
        { cal = 12.5, tag = 1, name = "milkywhites", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "goatmilk", weight = 12.5,},
        { cal = 25, tag = 1, name = "butter", weight = 25.0,},
        { name = "dairy",},
    },
    veggie = {
        { cal = 9.375, tag = 1, name = "garlic_cooked", weight = 9.375,},
        { cal = 9.375, tag = 1, name = "pepper_cooked", weight = 9.375,},
        { cal = 9.375, tag = 1, name = "pepper", weight = 9.375,},
        { cal = 9.375, tag = 1, name = "garlic", weight = 9.375,},
        { cal = 9.375, tag = 1, name = "onion_cooked", weight = 9.375,},
        { cal = 9.375, tag = 1, name = "onion", weight = 9.375,},
        { cal = 12.5, tag = 1, name = "rock_avocado_fruit_ripe", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "carrot", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "potato", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "carrot_cooked", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "cutlichen_cooked", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "cutlichen", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "cactus_meat_cooked", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "asparagus", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "potato_cooked", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "oceanfish_small_5_inv", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "asparagus_cooked", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "cactus_meat", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "tomato_cooked", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "rock_avocado_fruit_ripe_cooked", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "tomato", weight = 12.5,},
        { cal = 9.375, tag = 0.5, name = "kelp_dried", weight = 18.75,},
        { cal = 9.375, tag = 0.5, name = "kelp_cooked", weight = 18.75,},
        { cal = 9.375, tag = 0.5, name = "kelp", weight = 18.75,},
        { cal = 25, tag = 1, name = "eggplant", weight = 25.0,},
        { cal = 25, tag = 1, name = "corn_cooked", weight = 25.0,},
        { cal = 25, tag = 1, name = "corn", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_5_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "eggplant_cooked", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "cactus_flower", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "blue_cap_cooked", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "blue_cap", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "moon_cap", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "red_cap_cooked", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "red_cap", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "green_cap_cooked", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "moon_cap_cooked", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "green_cap", weight = 25.0,},
        { cal = 37.5, tag = 1, name = "pumpkin_cooked", weight = 37.5,},
        { cal = 37.5, tag = 1, name = "pumpkin", weight = 37.5,},
        { cal = 75, tag = 1, name = "mandrake", weight = 75.0,},
        { cal = 150, tag = 1, name = "cookedmandrake", weight = 150.0,},
        { name = "veggie",},
    },
    monster = {
        { cal = 18.75, tag = 1, name = "cookedmonstermeat", weight = 18.75,},
        { cal = 18.75, tag = 1, name = "monstermeat_dried", weight = 18.75,},
        { cal = 18.75, tag = 1, name = "monstermeat", weight = 18.75,},
        { cal = 25, tag = 1, name = "durian_cooked", weight = 25.0,},
        { cal = 25, tag = 1, name = "durian", weight = 25.0,},
        { name = "monster",},
    },
    fruit = {
        { cal = 9.375, tag = 1, name = "dragonfruit", weight = 9.375,},
        { cal = 9.375, tag = 1, name = "pomegranate", weight = 9.375,},
        { cal = 9.375, tag = 1, name = "dragonfruit_cooked", weight = 9.375,},
        { cal = 9.375, tag = 1, name = "pomegranate_cooked", weight = 9.375,},
        { cal = 12.5, tag = 1, name = "watermelon", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "watermelon_cooked", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "cave_banana_cooked", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "cave_banana", weight = 12.5,},
        { cal = 9.375, tag = 0.5, name = "berries_cooked", weight = 18.75,},
        { cal = 9.375, tag = 0.5, name = "berries", weight = 18.75,},
        { cal = 12.5, tag = 0.5, name = "fig_cooked", weight = 25.0,},
        { cal = 25, tag = 1, name = "durian_cooked", weight = 25.0,},
        { cal = 25, tag = 1, name = "durian", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "berries_juicy", weight = 25.0,},
        { cal = 25, tag = 1, name = "wormlight", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "fig", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "wormlight_lesser", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "berries_juicy_cooked", weight = 25.0,},
        { name = "fruit",},
    },
    frozen = {
        { cal = 2.34375, tag = 1, name = "ice", weight = 2.34375,},
        { cal = 25, tag = 1, name = "oceanfish_medium_8_inv", weight = 25.0,},
        { name = "frozen",},
    },
    fat = {
        { cal = 25, tag = 1, name = "butter", weight = 25.0,},
        { name = "fat",},
    },
    sweetener = {
        { cal = 12.5, tag = 3, name = "royal_jelly", weight = 4.1666666666667,},
        { cal = 9.375, tag = 1, name = "honey", weight = 9.375,},
        { tag = 1, name = "honeycomb",},
        { name = "sweetener",},
    },
    fish = {
        { cal = 9.375, tag = 1, name = "eel", weight = 9.375,},
        { cal = 9.375, tag = 1, name = "pondeel", weight = 9.375,},
        { cal = 9.375, tag = 1, name = "pondeel_cooked", weight = 9.375,},
        { cal = 9.375, tag = 1, name = "eel_cooked", weight = 9.375,},
        { cal = 12.5, tag = 1, name = "fish", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "fish_cooked", weight = 12.5,},
        { cal = 25, tag = 1, name = "oceanfish_medium_7_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_3_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "fishmeat", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_8_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_4_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "fishmeat_cooked", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_2_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_6_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_9_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_1_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_4_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_2_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_9_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "fishmeat_small_cooked", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_7_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "fishmeat_small", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "pondfish", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_6_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_3_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_1_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_8_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.25, name = "barnacle", weight = 50.0,},
        { cal = 12.5, tag = 0.25, name = "barnacle_cooked", weight = 50.0,},
        { name = "fish",},
        { tag = 1, name = "wobster_sheller_land",},
    },
    seed = {
        { cal = 9.375, tag = 1, name = "acorn", weight = 9.375,},
        { cal = 9.375, tag = 1, name = "acorn_cooked", weight = 9.375,},
        { name = "seed",},
    },
    inedible = {
        { cal = 9.375, tag = 1, name = "twigs", weight = 9.375,},
        { tag = 1, name = "boneshard",},
        { tag = 1, name = "lightninggoathorn",},
        { tag = 1, name = "nightmarefuel",},
        { name = "inedible",},
    },
    meats = {
        { cal = 12.5, tag = 1, name = "fish", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "plantmeat", weight = 12.5,},
        { cal = 12.5, tag = 1, name = "fish_cooked", weight = 12.5,},
        { cal = 18.75, tag = 1, name = "cookedmonstermeat", weight = 18.75,},
        { cal = 18.75, tag = 1, name = "monstermeat_dried", weight = 18.75,},
        { cal = 18.75, tag = 1, name = "monstermeat", weight = 18.75,},
        { cal = 18.75, tag = 1, name = "plantmeat_cooked", weight = 18.75,},
        { cal = 9.375, tag = 0.5, name = "eel_cooked", weight = 18.75,},
        { cal = 9.375, tag = 0.5, name = "pondeel_cooked", weight = 18.75,},
        { cal = 9.375, tag = 0.5, name = "eel", weight = 18.75,},
        { cal = 9.375, tag = 0.5, name = "pondeel", weight = 18.75,},
        { cal = 25, tag = 1, name = "oceanfish_medium_3_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "cookedmeat", weight = 25.0,},
        { cal = 25, tag = 1, name = "meat_dried", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_9_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "batnose", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_2_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_7_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_1_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "meat", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_6_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_4_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "fishmeat", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "batwing", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_8_inv", weight = 25.0,},
        { cal = 25, tag = 1, name = "fishmeat_cooked", weight = 25.0,},
        { cal = 25, tag = 1, name = "oceanfish_medium_9_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "pondfish", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "smallmeat", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "fishmeat_small", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "batnose_dried", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_8_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "drumstick", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_7_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "drumstick_cooked", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_3_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_6_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "smallmeat_dried", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_2_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "cookedsmallmeat", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "batwing_cooked", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_4_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "fishmeat_small_cooked", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "froglegs", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "froglegs_cooked", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "oceanfish_small_1_inv", weight = 25.0,},
        { cal = 12.5, tag = 0.5, name = "batnose_cooked", weight = 25.0,},
        { cal = 37.5, tag = 1, name = "trunk_summer", weight = 37.5,},
        { cal = 37.5, tag = 1, name = "trunk_winter", weight = 37.5,},
        { cal = 12.5, tag = 0.25, name = "barnacle", weight = 50.0,},
        { cal = 12.5, tag = 0.25, name = "barnacle_cooked", weight = 50.0,},
        { cal = 75, tag = 1, name = "trunk_cooked", weight = 75.0,},
        { tag = 1, name = "wobster_sheller_land",},
        { tag = 0.5, name = "mole",},
        { name = "meats",},
    },
    magic = {
        { cal = 75, tag = 1, name = "mandrake", weight = 75.0,},
        { cal = 150, tag = 1, name = "cookedmandrake", weight = 150.0,},
        { tag = 1, name = "nightmarefuel",},
        { name = "magic",},
    },
}
return tags